### ISSUE TITLE
SCH / RIE / LH - ONE Record Open Shipment Tracking API

### ISSUE THREAD

**Issue by mskopp** [IATA-Cargo/ONE-Record-Adoption#11]
### Project Objective

Connecting [DB Schenker](https://www.dbschenker.com/) forwarder transport management system via [Riege Software](https://www.riege.com/) as a ONE Record IT Service Provider with the [Lufthansa Cargo Open Shipment Tracking API](https://github.com/IATA-Cargo/ONE-Record-Adoption/issues/5) to interconnect two ONE Record Server Systems and provide LH milestone-based tracking information on shipment level into DB Schenker TMS System.

### Use Case Objective

Provide a full end-to-end ONE Record Shipment Tracking integration from forwarder TMS system via ONE Record IT Service Provider to a ONE Record airline system.
The infrastructure to be designed to be ready for production environment integration.

### Project Phase

E2E Pilot Project

### Accountable Person

@mskopp

### Company Information

The project was implemented and maintained by Riege Software in cooperation with DB Schenker and Lufthansa Cargo. Lufthansa Cargo providing the airline ONE Record Tracking System on the "airline" end and DB Schenker providing test data and production connectivity on the "forwarder" end. Riege Software operating a ONE Record server system for the forwarder part, consisting of a NE:ONE instance and an Integration Layer component.

Technical coordination at Riege Software: @kschmengler

### ONE Record Data Model

- [X] Airline Core Ontology
- [ ] Shipper's Letter of Instruction
- [ ] Cargo Distribution
- [ ] CO2 Emission
- [ ] Billing & Settlement
- [ ] ULD Tracking
- [ ] Interactive Cargo
- [ ] Dangerous Goods
- [ ] Pharmaceutical
- [ ] Advanced Cargo Information
- [ ] Ground Handling

### ONE Record API Features

- [X] PUB/SUB
- [ ] LO update
- [ ] Access delegation
- [ ] Security
- [X] Event
- [ ] Audit train / Versioning
- [X] Access Control
- [ ] Cascading status update - Pub/Sub in multi chain
- [ ] Data integrity / non repudiation with RDF
- [ ] SHACL shapes
- [ ] IoT updates
- [ ] Rich data

### Lessons Learned

The learnings are
* insights about ONE Record Event mapping to traditional TMS event processing
* technical details about NE:ONE server connectivity to 3rd party ONE Record Server
* technical details about NE:ONE server proxy functionality with an Integration Layer implementation
