### ISSUE TITLE
LH - ONE Record Open Shipment Tracking API

### ISSUE THREAD

**Issue by DrPhilippBillion** [IATA-Cargo/ONE-Record-Adoption#5]
### Project Objective

The Lufthansa Cargo Open Shipment Tracking API provides traditional milestone-based tracking information on Shipment level, but is fully compliant with the ONE Record Piece-centric data model. As it covers mostly the currently available milestones, it will be extended wit additional data types according to customers demands.

### Use Case Objective

Provide a full-fledge operational showcase for ONE Record under production environment.

### Project Phase

Live Production

### Start Date

25. April 2024

### End Date

no end

### Accountable Person

@ddoeppner

### Company Information

The project was implemented and is maintained by Lufthansa Cargo. As it is an "open" API, nor direct piloting partners were required. Still, any feedback fron the industry is welcome.

### Standard Version

Data Model v3.0; API v2.0

### ONE Record Data Model

- [X] Airline Core Ontology
- [ ] Shipper's Letter of Instruction
- [ ] Cargo Distribution
- [ ] CO2 Emission
- [ ] Billing & Settlement
- [ ] ULD Tracking
- [ ] Interactive Cargo
- [ ] Dangerous Goods
- [ ] Pharmaceutical
- [ ] Advanced Cargo Information
- [ ] Ground Handling

### ONE Record API Features

- [X] PUB/SUB
- [ ] LO update
- [ ] Access delegation
- [X] Security
- [X] Event
- [ ] Audit train / Versioning
- [X] Access Control
- [ ] Cascading status update - Pub/Sub in multi chain
- [ ] Data integrity / non repudiation with RDF
- [ ] SHACL shapes
- [ ] IoT updates
- [ ] Rich data

### Lessons Learned

The learnings from this project were a major driver behind Data Model v3 and API v2. The complete approach was documented in https://github.com/digital-cargo/good-practice-shipment-tracking .
