### ISSUE TITLE
CV- 1R PoC

### ISSUE THREAD

**Issue by CVTRIBE** [IATA-Cargo/ONE-Record-Adoption#9]
### Project Objective

**Objective:** The main objective of this use case is to demonstrate that FWB/FHL equivalents can be shared using 1R standard.

**Background:** This use case is derived from the current challenges we are facing in regards to data integrity when receiving/transmitting FWBs.

**Partnership**: We are currently looking for partners, specifically a forwarder and a ground handler, to perform this Proof of Concept (PoC) together with CV and IBS.

### Use Case Objective

The goal of this use case is to share _MAWB_ and _HAWB_ data via ONE Record.

Detailed proposed roadmap:

**Phase 1**- Forwarder to notify CV/IBS on creation of AWB LO. CV/IBS 1R server to retrieve this data and process it in our CMS.
**Phase 2**- CV to perform updates in our CMS for forwarder/CCS on AWB LOs and information to be patched to Forwarder/CCS 1R server
**Phase 3**- Similar to phase 1 and 2 on HAWB level (Creation/Update)
**Phase 4**- Error Handlings

**To achieve this, we are currently looking for a forwarder + ground handler to perform this PoC together with CV and IBS.**

For more information, please reach out to bernardo.trindadecerveira@cargolux.com 

### Project Phase

Exploration/ PoC

### Start Date

01/01/2024

### End Date

31/05/2025

### Accountable Person

Bernardo Cerveira

### Company Information

FF: DB Schenker
Airline: Cargolux Airlines
Airline service provider: IBS
Freight Forwarder service provider: Riege Software
GHA:_TBD

### ONE Record Data Model

- [X] Airline Core Ontology
- [ ] Shipper's Letter of Instruction
- [ ] Cargo Distribution
- [ ] CO2 Emission
- [ ] Billing & Settlement
- [ ] ULD Tracking
- [ ] Interactive Cargo
- [ ] Dangerous Goods
- [ ] Pharmaceutical
- [X] Advanced Cargo Information
- [X] Ground Handling

### ONE Record API Features

- [X] PUB/SUB
- [X] LO update
- [X] Access delegation
- [ ] Security
- [X] Event
- [X] Audit train / Versioning
- [X] Access Control
- [X] Cascading status update - Pub/Sub in multi chain
- [ ] Data integrity / non repudiation with RDF
- [ ] SHACL shapes
- [ ] IoT updates
- [ ] Rich data
